name: Container Security Scan
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs